### ISSUE TITLE
social login throwing 401 after changing google client ID and secret

### ISSUE THREAD

**Issue by abhinavpawar93** [naturalprogrammer/spring-lemon#30]
After changing the client ID and secret the code returned by google is little different and social API is throwing 401. 
Any help would be appreciated. Do let me know if any other info is required. Thanks in advance.

**Comment by naturalprogrammer** [comment]
Strange. Help wanted if anyone else can try and reproduce the issue...

**Comment by abhinavpawar93** [comment]
Can you also help me implement the same social login via mobile apps. As the auth token returned by them is different and throws 401 when passing to get Context

**Comment by naturalprogrammer** [comment]
I've no idea on mobile apps and how they would be different. Could you please explain what's the exact issue and how Spring Lemon could support this you think?

**Comment by abhinavpawar93** [comment]
Hi, thanks for the reply. 
Let me explain in detail:
When we hit this api: /oauth2/authorization/google (For login using Google via web browser)
we are expecting **code** from google auth on this endpoint : /login/oauth2/code/google. Right?
Then an auth token is generated and user is redirected to this end point with access token (which can be exchanged with an Access token using getContext API) : /social-login-success?token

But, in mobile devices we use Google sdk for login which returns auth code to our app, and not on our server end point which is (/login/oauth2/code/google). How can I use this code to generate access token for that particular code.

Any help will be appreciated as I am stuck with this from past 3 days. BTW thanks for the amazing library. +1

**Comment by naturalprogrammer** [comment]
Not sure how to support it. But why do you use the Google SDK? Why not the server endpoint, just like a webapp? Hope your app is cookie enabled.

**Comment by abhinavpawar93** [comment]
Mobile apps use native sdk for social login. Anyway I got it fixed by
getting idToken from the client and then hitting respective google and
facebook details api. Then registered that user and returned the response
to client with access token and signup response. You can close this issue.

**Comment by naturalprogrammer** [comment]
Ok, thanks for posting the solution -- it might help others. However, I still have a question: you'll then need to code the social login in Android/iOS -- separately for each Google, Feacbook, GitHub ...? What's the exact problem in using the server redirects instead, just like web applications?

**Comment by abhinavpawar93** [comment]
Mobile devices use sdks for these social logins. Hence no server redirects. Thanks for the help.
